# Use postgres/example user/password credentials
version: '3.1'

services:
  web:
    build: .
    ports:
     - "5000:5000"
  # redis:
  #   image: "redis:alpine"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
